const {test}=require('node:test'),assert=require('node:assert/strict');const Player=require('../sutro-player.js');
class Track{constructor(label){this.label=label;this.mode='disabled';this.items=[];}get cues(){return this.mode==='disabled'?null:this.items;}addCue(cue){this.items.push(cue);}removeCue(cue){this.items.splice(this.items.indexOf(cue),1);}}
class Cue{constructor(start,end,text){Object.assign(this,{start,end,text});}}
function fixture(){const list=new EventTarget(),stage=new EventTarget(),changes=[],sources=[];const video={textTracks:list,addTextTrack:(kind,label)=>new Track(label)};const p=new Player({video,theme:{},stage,Cue,onCaptionChange:x=>changes.push(x),onSourceChange:x=>sources.push(x),onPause:()=>{}});return {p,list,changes,sources,stage};}
test('native CC toggles remain off while later Qwen windows replace cues',()=>{const {p,list,changes}=fixture();p.select('qwen-cache',true);p.setCues('qwen-cache',[{start:0,end:20,text:'第一句'}]);const track=p.track('qwen-cache');assert.equal(track.mode,'showing');track.mode='disabled';list.dispatchEvent(new Event('change'));assert.deepEqual(changes,[false]);p.setCues('qwen-cache',[{start:20,end:40,text:'第二句'}]);assert.equal(track.mode,'disabled');assert.equal(track.items.length,1);});
test('platform and local tracks share one active source; caption menu source changes propagate',()=>{const {p,list,sources}=fixture();p.setCues('platform',[{start:0,end:1,text:'官方'}]);p.setCues('qwen-cache',[{start:0,end:1,text:'本地'}]);p.select('qwen-cache',true);assert.equal(p.track('platform').mode,'disabled');p.track('qwen-cache').mode='disabled';p.track('platform').mode='showing';list.dispatchEvent(new Event('change'));assert.deepEqual(sources,['platform']);assert.equal(p.source,'platform');});
test('clearing a lecture removes all old cues without changing the caption preference',()=>{const {p,list,changes}=fixture();p.setCues('platform',[{start:0,end:1,text:'旧课次'}]);p.clear();list.dispatchEvent(new Event('change'));assert.deepEqual(changes,[]);assert.equal(p.track('platform').items.length,0);p.setCues('platform',[{start:0,end:2,text:'新课次'}]);assert.equal(p.track('platform').mode,'showing');assert.equal(p.track('platform').cues[0].text,'新课次');});
test('invalid cues are ignored and changing position applies to every track',()=>{const {p}=fixture();p.setCues('qwen-cache',[{start:0,end:0,text:'invalid'},{start:2,end:3,text:'valid'}]);p.position(true);assert.equal(p.track('qwen-cache').items.length,1);assert.equal(p.track('qwen-cache').items[0].line,0);});

test('CC user intent is captured before a pending native change event and the next window',()=>{const {p,stage,changes}=fixture();p.select('qwen-cache',true);p.setCues('qwen-cache',[{start:0,end:20,text:'第一句'}]);stage.dispatchEvent(new Event('mediatogglesubtitlesrequest'));p.setCues('qwen-cache',[{start:20,end:40,text:'第二句'}]);assert.equal(p.track('qwen-cache').mode,'disabled');assert.equal(p.enabled,false);assert.deepEqual(changes,[false]);});

test('disabled tracks do not retain stale cues after a window update or lecture clear',()=>{const {p}=fixture();p.select('qwen-cache',false);p.setCues('qwen-cache',[{start:0,end:10,text:'旧窗口'}]);assert.equal(p.track('qwen-cache').cues,null);p.setCues('qwen-cache',[{start:10,end:20,text:'新窗口'}]);assert.equal(p.track('qwen-cache').items.length,1);p.clear();assert.equal(p.track('qwen-cache').items.length,0);});
